// ATLProject1.idl : IDL source for ATLProject1
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLProject1.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(094D42D4-ADA8-489C-A037-9DE139651044),
	version(1.0),
]
library ATLProject1Lib
{
	importlib("stdole2.tlb");
};

